apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
spec:
  type: ClusterIP
  selector:
    app: kafka
  ports:
    - name: plaintext
      protocol: TCP
      port: 9092
      targetPort: 9092
    - name: controller
      protocol: TCP
      port: 29093
      targetPort: 29093
  clusterIP: None
